// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKElrDEYiWj1Ffpd-cEIlLnKv3A5YtxWA',
    appId: '1:422360690348:web:72d65785eab5ea6aaff909',
    messagingSenderId: '422360690348',
    projectId: 'tradeit-cc540',
    authDomain: 'tradeit-cc540.firebaseapp.com',
    databaseURL: 'https://tradeit-cc540-default-rtdb.firebaseio.com',
    storageBucket: 'tradeit-cc540.appspot.com',
    measurementId: 'G-QMXXSWQWHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVpLQS-8j3BQa-cc53sWE1FFZdH2qGcXg',
    appId: '1:422360690348:android:f61139e73d69e84faff909',
    messagingSenderId: '422360690348',
    projectId: 'tradeit-cc540',
    databaseURL: 'https://tradeit-cc540-default-rtdb.firebaseio.com',
    storageBucket: 'tradeit-cc540.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxVtRg6FS0awD0jjMx8BZUiKfz9qM52Oo',
    appId: '1:422360690348:ios:4963c2d6f66f6fdbaff909',
    messagingSenderId: '422360690348',
    projectId: 'tradeit-cc540',
    databaseURL: 'https://tradeit-cc540-default-rtdb.firebaseio.com',
    storageBucket: 'tradeit-cc540.appspot.com',
    iosClientId: '422360690348-qmf264qnpk79s1oeugtau4tcaed6tqbh.apps.googleusercontent.com',
    iosBundleId: 'com.commerce.commerceHub',
  );
}
